// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: play_history.sql

package sqlc

import (
	"context"
	"time"
)

const clearPlayHistory = `-- name: ClearPlayHistory :execrows
DELETE FROM play_history WHERE context_type = ? AND context_key = ?
`

type ClearPlayHistoryParams struct {
	ContextType string
	ContextKey  string
}

func (q *Queries) ClearPlayHistory(ctx context.Context, arg ClearPlayHistoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearPlayHistory, arg.ContextType, arg.ContextKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearPlayHistoryByPlaylist = `-- name: ClearPlayHistoryByPlaylist :execrows
DELETE FROM play_history WHERE context_type = 'playlist' AND context_key = ?
`

func (q *Queries) ClearPlayHistoryByPlaylist(ctx context.Context, contextKey string) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearPlayHistoryByPlaylist, contextKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearPlayHistoryByTag = `-- name: ClearPlayHistoryByTag :execrows
DELETE FROM play_history WHERE context_type = 'tag' AND context_key = ?
`

func (q *Queries) ClearPlayHistoryByTag(ctx context.Context, contextKey string) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearPlayHistoryByTag, contextKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countPlayHistory = `-- name: CountPlayHistory :one
SELECT COUNT(*) FROM play_history WHERE context_type = ? AND context_key = ?
`

type CountPlayHistoryParams struct {
	ContextType string
	ContextKey  string
}

func (q *Queries) CountPlayHistory(ctx context.Context, arg CountPlayHistoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlayHistory, arg.ContextType, arg.ContextKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePlayHistoryEntry = `-- name: DeletePlayHistoryEntry :execrows
DELETE FROM play_history WHERE context_type = ? AND context_key = ? AND song_id = ?
`

type DeletePlayHistoryEntryParams struct {
	ContextType string
	ContextKey  string
	SongID      int64
}

func (q *Queries) DeletePlayHistoryEntry(ctx context.Context, arg DeletePlayHistoryEntryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePlayHistoryEntry, arg.ContextType, arg.ContextKey, arg.SongID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listPlayHistory = `-- name: ListPlayHistory :many
SELECT song_id, played_at, play_count FROM play_history
WHERE context_type = ? AND context_key = ?
ORDER BY played_at DESC, id DESC
LIMIT ?
`

type ListPlayHistoryParams struct {
	ContextType string
	ContextKey  string
	Limit       int64
}

type ListPlayHistoryRow struct {
	SongID    int64
	PlayedAt  time.Time
	PlayCount int64
}

func (q *Queries) ListPlayHistory(ctx context.Context, arg ListPlayHistoryParams) ([]ListPlayHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayHistory, arg.ContextType, arg.ContextKey, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayHistoryRow{}
	for rows.Next() {
		var i ListPlayHistoryRow
		if err := rows.Scan(&i.SongID, &i.PlayedAt, &i.PlayCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordPlay = `-- name: RecordPlay :exec
INSERT INTO play_history (context_type, context_key, song_id, played_at, play_count)
VALUES (?, ?, ?, ?, 1)
ON CONFLICT(context_type, context_key, song_id) DO UPDATE SET
    played_at = excluded.played_at,
    play_count = play_history.play_count + 1
`

type RecordPlayParams struct {
	ContextType string
	ContextKey  string
	SongID      int64
	PlayedAt    time.Time
}

func (q *Queries) RecordPlay(ctx context.Context, arg RecordPlayParams) error {
	_, err := q.db.ExecContext(ctx, recordPlay,
		arg.ContextType,
		arg.ContextKey,
		arg.SongID,
		arg.PlayedAt,
	)
	return err
}

const trimPlayHistory = `-- name: TrimPlayHistory :exec
DELETE FROM play_history
WHERE play_history.context_type = ?
  AND play_history.context_key = ?
  AND play_history.id NOT IN (
    SELECT ph.id FROM play_history ph
    WHERE ph.context_type = ? AND ph.context_key = ?
    ORDER BY ph.played_at DESC, ph.id DESC
    LIMIT ?
)
`

type TrimPlayHistoryParams struct {
	ContextType   string
	ContextKey    string
	ContextType_2 string
	ContextKey_2  string
	Limit         int64
}

func (q *Queries) TrimPlayHistory(ctx context.Context, arg TrimPlayHistoryParams) error {
	_, err := q.db.ExecContext(ctx, trimPlayHistory,
		arg.ContextType,
		arg.ContextKey,
		arg.ContextType_2,
		arg.ContextKey_2,
		arg.Limit,
	)
	return err
}
