// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: song_tags.sql

package sqlc

import (
	"context"
)

const countSongsByTag = `-- name: CountSongsByTag :one
SELECT COUNT(*) FROM song_tag_links WHERE tag_id = ?
`

func (q *Queries) CountSongsByTag(ctx context.Context, tagID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSongsByTag, tagID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSongTag = `-- name: CreateSongTag :execlastid
INSERT INTO song_tags (name, color) VALUES (?, ?)
`

type CreateSongTagParams struct {
	Name  string
	Color string
}

func (q *Queries) CreateSongTag(ctx context.Context, arg CreateSongTagParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createSongTag, arg.Name, arg.Color)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteSongTag = `-- name: DeleteSongTag :exec
DELETE FROM song_tags WHERE id = ?
`

func (q *Queries) DeleteSongTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSongTag, id)
	return err
}

const getSongTagByID = `-- name: GetSongTagByID :one
SELECT id, name, color, created_at FROM song_tags WHERE id = ?
`

func (q *Queries) GetSongTagByID(ctx context.Context, id int64) (SongTag, error) {
	row := q.db.QueryRowContext(ctx, getSongTagByID, id)
	var i SongTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getSongTagByName = `-- name: GetSongTagByName :one
SELECT id, name, color, created_at FROM song_tags WHERE name = ?
`

func (q *Queries) GetSongTagByName(ctx context.Context, name string) (SongTag, error) {
	row := q.db.QueryRowContext(ctx, getSongTagByName, name)
	var i SongTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getTagsBySongID = `-- name: GetTagsBySongID :many
SELECT t.id, t.name, t.color, t.created_at
FROM song_tags t
JOIN song_tag_links l ON t.id = l.tag_id
WHERE l.song_id = ?
ORDER BY t.name
`

func (q *Queries) GetTagsBySongID(ctx context.Context, songID int64) ([]SongTag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsBySongID, songID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SongTag{}
	for rows.Next() {
		var i SongTag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkSongTag = `-- name: LinkSongTag :exec
INSERT OR IGNORE INTO song_tag_links (song_id, tag_id) VALUES (?, ?)
`

type LinkSongTagParams struct {
	SongID int64
	TagID  int64
}

func (q *Queries) LinkSongTag(ctx context.Context, arg LinkSongTagParams) error {
	_, err := q.db.ExecContext(ctx, linkSongTag, arg.SongID, arg.TagID)
	return err
}

const unlinkAllBySong = `-- name: UnlinkAllBySong :exec
DELETE FROM song_tag_links WHERE song_id = ?
`

func (q *Queries) UnlinkAllBySong(ctx context.Context, songID int64) error {
	_, err := q.db.ExecContext(ctx, unlinkAllBySong, songID)
	return err
}

const unlinkSongTag = `-- name: UnlinkSongTag :exec
DELETE FROM song_tag_links WHERE song_id = ? AND tag_id = ?
`

type UnlinkSongTagParams struct {
	SongID int64
	TagID  int64
}

func (q *Queries) UnlinkSongTag(ctx context.Context, arg UnlinkSongTagParams) error {
	_, err := q.db.ExecContext(ctx, unlinkSongTag, arg.SongID, arg.TagID)
	return err
}

const updateSongTag = `-- name: UpdateSongTag :exec
UPDATE song_tags SET name = ?, color = ? WHERE id = ?
`

type UpdateSongTagParams struct {
	Name  string
	Color string
	ID    int64
}

func (q *Queries) UpdateSongTag(ctx context.Context, arg UpdateSongTagParams) error {
	_, err := q.db.ExecContext(ctx, updateSongTag, arg.Name, arg.Color, arg.ID)
	return err
}
