// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: song_artists.sql

package sqlc

import (
	"context"
	"time"
)

const countArtistSongs = `-- name: CountArtistSongs :one
SELECT COUNT(*) FROM song_artists WHERE artist_id = ?
`

func (q *Queries) CountArtistSongs(ctx context.Context, artistID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArtistSongs, artistID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSongArtistsBySong = `-- name: DeleteSongArtistsBySong :exec
DELETE FROM song_artists WHERE song_id = ?
`

func (q *Queries) DeleteSongArtistsBySong(ctx context.Context, songID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSongArtistsBySong, songID)
	return err
}

const getArtistByName = `-- name: GetArtistByName :one
SELECT id, name, normalized_key, created_at FROM artists WHERE name = ? COLLATE NOCASE
`

func (q *Queries) GetArtistByName(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtistByName, name)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedKey,
		&i.CreatedAt,
	)
	return i, err
}

const getArtistByNormalizedKey = `-- name: GetArtistByNormalizedKey :one
SELECT id, name, normalized_key, created_at FROM artists WHERE normalized_key = ?
`

func (q *Queries) GetArtistByNormalizedKey(ctx context.Context, normalizedKey string) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtistByNormalizedKey, normalizedKey)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedKey,
		&i.CreatedAt,
	)
	return i, err
}

const getArtistsBySongID = `-- name: GetArtistsBySongID :many
SELECT a.id AS artist_id, a.name AS artist_name, a.normalized_key AS artist_normalized_key,
       a.created_at AS artist_created_at,
       sa.role, sa.position
FROM song_artists sa
JOIN artists a ON a.id = sa.artist_id
WHERE sa.song_id = ?
ORDER BY sa.position, a.name
`

type GetArtistsBySongIDRow struct {
	ArtistID            int64
	ArtistName          string
	ArtistNormalizedKey string
	ArtistCreatedAt     time.Time
	Role                string
	Position            int64
}

func (q *Queries) GetArtistsBySongID(ctx context.Context, songID int64) ([]GetArtistsBySongIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getArtistsBySongID, songID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetArtistsBySongIDRow{}
	for rows.Next() {
		var i GetArtistsBySongIDRow
		if err := rows.Scan(
			&i.ArtistID,
			&i.ArtistName,
			&i.ArtistNormalizedKey,
			&i.ArtistCreatedAt,
			&i.Role,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkSongArtist = `-- name: LinkSongArtist :exec
INSERT INTO song_artists (song_id, artist_id, role, position) VALUES (?, ?, ?, ?)
ON CONFLICT(song_id, artist_id, role) DO UPDATE SET position = excluded.position
`

type LinkSongArtistParams struct {
	SongID   int64
	ArtistID int64
	Role     string
	Position int64
}

func (q *Queries) LinkSongArtist(ctx context.Context, arg LinkSongArtistParams) error {
	_, err := q.db.ExecContext(ctx, linkSongArtist,
		arg.SongID,
		arg.ArtistID,
		arg.Role,
		arg.Position,
	)
	return err
}

const upsertArtist = `-- name: UpsertArtist :exec
INSERT INTO artists (name, normalized_key) VALUES (?, ?)
ON CONFLICT(normalized_key) DO UPDATE SET name = excluded.name
`

type UpsertArtistParams struct {
	Name          string
	NormalizedKey string
}

func (q *Queries) UpsertArtist(ctx context.Context, arg UpsertArtistParams) error {
	_, err := q.db.ExecContext(ctx, upsertArtist, arg.Name, arg.NormalizedKey)
	return err
}
